-- MySQL Script generated by MySQL Workbench
-- 08/22/14 10:51:53
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema university
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `university` DEFAULT CHARACTER SET utf8 ;
USE `university` ;

-- -----------------------------------------------------
-- Table `university`.`faculties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`faculties` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `university`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`departments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `faculty_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_departments_faculties_idx` (`faculty_id` ASC),
  CONSTRAINT `fk_departments_faculties`
    FOREIGN KEY (`faculty_id`)
    REFERENCES `university`.`faculties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `university`.`professors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`professors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `department_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_professors_departments1_idx` (`department_id` ASC),
  CONSTRAINT `fk_professors_departments1`
    FOREIGN KEY (`department_id`)
    REFERENCES `university`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `university`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`courses` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `department_id` INT(11) NOT NULL,
  `professor_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_course_departments1_idx` (`department_id` ASC),
  INDEX `fk_course_professors1_idx` (`professor_id` ASC),
  CONSTRAINT `fk_course_departments1`
    FOREIGN KEY (`department_id`)
    REFERENCES `university`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_course_professors1`
    FOREIGN KEY (`professor_id`)
    REFERENCES `university`.`professors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `university`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`students` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `faculty_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_students_faculties1_idx` (`faculty_id` ASC),
  CONSTRAINT `fk_students_faculties1`
    FOREIGN KEY (`faculty_id`)
    REFERENCES `university`.`faculties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `university`.`courses_students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`courses_students` (
  `course_id` INT(11) NOT NULL,
  `student_id` INT(11) NOT NULL,
  INDEX `fk_courses_students_course1_idx` (`course_id` ASC),
  INDEX `fk_courses_students_students1_idx` (`student_id` ASC),
  PRIMARY KEY (`course_id`, `student_id`),
  CONSTRAINT `fk_courses_students_course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `university`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_courses_students_students1`
    FOREIGN KEY (`student_id`)
    REFERENCES `university`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `university`.`titles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`titles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `university`.`professors_titles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`professors_titles` (
  `professor_id` INT(11) NOT NULL,
  `title_id` INT(11) NOT NULL,
  PRIMARY KEY (`professor_id`, `title_id`),
  INDEX `fk_professors_titles_professors1_idx` (`professor_id` ASC),
  INDEX `fk_professors_titles_titles1_idx` (`title_id` ASC),
  CONSTRAINT `fk_professors_titles_professors1`
    FOREIGN KEY (`professor_id`)
    REFERENCES `university`.`professors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professors_titles_titles1`
    FOREIGN KEY (`title_id`)
    REFERENCES `university`.`titles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
